controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: 'fr|en|pt|ja|ht|ar|es|de|ko|it|ru|mq'
    defaults:
        _locale: 'fr'

